title: " "  

description: >
  <img src="assets/images/logo.jpg" alt="Company Logo" width="150"><br><br>
  <h2 style="font-size:1.5em; color:#111; margin:0; text-align:center;">Barite Solar Project</h2><br>
  <img src="assets/images/site2.jpg" alt="Site Plan" width="300"><br><br>
  <img src="assets/images/panels.jpg" alt="Panels" width="300"><br><br>

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme











