title: " "  

description: >
  <img src="assets/images/logo2.jpg" alt="Company Logo" width="150"><br><br>
  <h2 style="font-size:2.25em; color:#111; margin:0; text-align:center;">Barite Solar</h2><br>
  <img src="assets/images/site2.jpg" alt="Site Plan" width="300"><br><br>
  <img src="assets/images/panels.jpg" alt="Panels" width="300"><br><br>
  <p style="font-size: 0.9em; color: #444; margin-bottom: 40px;">
  Ground cover maintains soil quality and reduces runoff.
  </p>


remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

include:
  - assets/css/custom.css











