title: " "  

description: >
  <img src="assets/images/logo.jpg" alt="Company Logo" width="150"><br><br>
  <h2 style="font-size:5em; color:#111; margin:0;">Barite Solar Project</h2><br>
  <img src="assets/images/site2.jpg" alt="Site Plan" width="160"><br><br>
  A developing solar project overview.
  
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme











